### ISSUE TITLE
Use version numbers on releases

### ISSUE THREAD

**Issue by dllud** [0xver/ether#2]
Hi!

(Thanks for building this. It's super helpful.)

Could you please tag releases with some kind of incremental version number? This would help me (and others) package this software.
(The only release so far is just tagged as "latest".)

**Comment by dllud** [comment]
I see that you are tracking versions on [setup.py](https://github.com/0xver/ether/blob/master/setup.py). It would be helpful if you could add a tag on git with the corresponding version number everytime you make an increment there.

**Comment by 0xver** [comment]
You can follow the releases on PyPi but I will start tagging versions herein.

**Comment by dllud** [comment]
Thanks!
Having them tagged allows writing much cleaner packaging scripts.
